// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGSCM051FwoYsi60X98KnlHWT3lRwIfZ8',
    appId: '1:1020194338094:web:23ac3a60d986ce1187f6bf',
    messagingSenderId: '1020194338094',
    projectId: 'currencyconversion-21d09',
    authDomain: 'currencyconversion-21d09.firebaseapp.com',
    databaseURL: 'https://currencyconversion-21d09-default-rtdb.firebaseio.com',
    storageBucket: 'currencyconversion-21d09.appspot.com',
    measurementId: 'G-VFN45KH2LT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4ViSmzXkF9l77xt85USA929yt3G-vNPA',
    appId: '1:1020194338094:android:663949b4a90ef16b87f6bf',
    messagingSenderId: '1020194338094',
    projectId: 'currencyconversion-21d09',
    databaseURL: 'https://currencyconversion-21d09-default-rtdb.firebaseio.com',
    storageBucket: 'currencyconversion-21d09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5ODRRZ8r8_bAg1Bo2EJs3gXkK4NuMglo',
    appId: '1:1020194338094:ios:c1b6a3f5706c4c5d87f6bf',
    messagingSenderId: '1020194338094',
    projectId: 'currencyconversion-21d09',
    databaseURL: 'https://currencyconversion-21d09-default-rtdb.firebaseio.com',
    storageBucket: 'currencyconversion-21d09.appspot.com',
    iosBundleId: 'com.example.currencyConversion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5ODRRZ8r8_bAg1Bo2EJs3gXkK4NuMglo',
    appId: '1:1020194338094:ios:1ca552ac1ac8b75687f6bf',
    messagingSenderId: '1020194338094',
    projectId: 'currencyconversion-21d09',
    databaseURL: 'https://currencyconversion-21d09-default-rtdb.firebaseio.com',
    storageBucket: 'currencyconversion-21d09.appspot.com',
    iosBundleId: 'com.example.currencyConversion.RunnerTests',
  );
}
